debug: ${SCIP_DEBUG:false}

logging:
  file:
    path: ${SCIP_LOGGING_FILE_PATH:./log}

server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: spring-cloud-in-practice-user
  config:
    import: "optional:consul:"
  datasource:
    url: ${SCIP_SPRING_DATASOURCE_URL:jdbc:mysql://localhost/scip_user}
    username: ${SCIP_SPRING_DATASOURCE_USERNAME:root}
    password: ${SCIP_SPRING_DATASOURCE_PASSWORD:}
  jpa:
    open-in-view: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${SCIP_SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SCIP_SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
      config:
        enabled: true
        prefixes:
          - spring-cloud-in-practice
        name: user
        format: YAML

management:
  endpoints:
    web:
      exposure:
        include: "*"
