debug: ${SCIP_DEBUG:false}

logging:
  file:
    path: ${SCIP_LOGGING_FILE_PATH:./log}

server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: spring-cloud-in-practice-gateway
  config:
    import: "optional:consul:"
  redis:
    host: ${SCIP_SPRING_REDIS_HOST:localhost}
    port: ${SCIP_SPRING_REDIS_PORT:6379}
    password: ${SCIP_SPRING_REDIS_PASSWORD:}
    connectTimeout: 5s
  session:
    store-type: redis
    timeout: 8h
    redis:
      namespace: scip:session
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${SCIP_SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SCIP_SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
      config:
        enabled: true
        prefixes:
          - spring-cloud-in-practice
        name: gateway
        format: YAML

feign:
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      spring-cloud-in-practice-auth:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
